### ISSUE TITLE
error

### ISSUE THREAD

**Issue by NikiN2** [julianxhokaxhiu/gitbook-plugin-summary#1]
When try to start
PluginError: Error with plugin "summary": Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

CLI version: 2.3.2
GitBook version: 3.2.3
node v4.6.0

book.json:

{
    "title": "!",
    "author": "ДГ",
    "plugins": [
             "image-captions","parts-autoindex","back-to-top-button","summary"
    ],
    "pluginsConfig": {
      "image-captions": {
          "caption": "Рис _PAGE_LEVEL_._PAGE_IMAGE_NUMBER_ - _CAPTION_",
		  "variable_name": "pictures"
      },
     "parts-autoindex": {
            "level": 2,
            "trim": 1,
            "offset": -1
        }
  }
}

**Comment by julianxhokaxhiu** [comment]
Hi, can you please retry it now? I had to refactor the whole plugin.

**Comment by julianxhokaxhiu** [comment]
Also, your NodeJS version looks a little bit older. Please update to the latest LTS version.

**Comment by NikiN2** [comment]
Sorry for the lack of response.  I updated nodejs
Now everything is ok
