### ISSUE TITLE
The summary plugin doesn't work in the first executing

### ISSUE THREAD

**Issue by zpfang** [julianxhokaxhiu/gitbook-plugin-summary#10]
The summary plugin doesn't work in the first executing the gitbook serve command, the secode one it works, the first one uses the summary file generated by the laste time.

**Comment by julianxhokaxhiu** [comment]
For me actually it works right away. May I ask which version are you testing? I'm on `0.1.2`.

**Comment by julianxhokaxhiu** [comment]
Tried also `0.2.0`, works fine as well.

**Comment by zpfang** [comment]
I'm testing on 0.2.0 version, 
execute the gitbook serve command firstly, the SUMMARY file is generated right away, but the html page doesn't work. 
Are you testing in the  html page? 
My testings step are:
One step, clean up the SUMMARY.md file or delete the SUMMARY.md file, 
then execute gitbook serve, the localhost:4000 is not showing as the SUMMARY.md.
last, excute gitbook serve secondly, all works fine as well.

**Comment by julianxhokaxhiu** [comment]
I found some time to replicate the bug and I am finally able to trigger it correctly.

Also I am trying to debug and understand where the issue lives, but it seems that is something inside of Gitbook CLI. I am following the integration pattern as they describe, but it seems that there is a race condition within their Promise handling.

I would suggest to escalate this into their Github repo.
