### ISSUE TITLE
info: No version specified, resolve plugin summary

### ISSUE THREAD

**Issue by morethink** [julianxhokaxhiu/gitbook-plugin-summary#4]
info: No version specified, resolve plugin summary

Found no satisfactory version for plugin summary

**Comment by julianxhokaxhiu** [comment]
Sorry I don't get what is the issue.

**Comment by morethink** [comment]
when I use add the  
```
 "plugins": [
    "summary"
  ]
```
to my book.json,the erro is 
![image](https://user-images.githubusercontent.com/20169736/31474503-ce53f0f4-af2d-11e7-9f50-059b11471a66.png)

**Comment by julianxhokaxhiu** [comment]
You have to learn how to write a report.

Please provide your package.json, your book.json and in case you have one, a repository when I could check your code. And last but not least, a full log dump since the moment you write your command until the error appears.

**Comment by morethink** [comment]
Thank you, I will write a detailed  report to you.
The problem has been solved, because the version of the node is not the required version.

But now there is an unexpected phenomenon, summary.md is not what we expected.
My directory structure is
![image](https://user-images.githubusercontent.com/20169736/31544620-3fd83408-b04e-11e7-8259-477a47400ce1.png)


After using the plugin, the summary.md is

![image](https://user-images.githubusercontent.com/20169736/31544627-46453db8-b04e-11e7-96b5-c385cfe22089.png)
My Gitbook is 

![image](https://user-images.githubusercontent.com/20169736/31545120-a890e8da-b050-11e7-83ad-c4c5a93704ab.png)


book.json
```
{
  "title": "一个程序员的自我修养",
  "author": "李文浩",
  "description": "思考",
  "language": "zh-hans",
  "extension": null,
  "generator": "website",
  "links": {
    "sharing": {
      "all": null,
      "facebook": null,
      "google": null,
      "twitter": null,
      "weibo": null
    }
  },
  "output": null,
  "pdf": {
    "fontSize": 12,
    "footerTemplate": null,
    "headerTemplate": null,
    "margin": {
      "bottom": 36,
      "left": 62,
      "right": 62,
      "top": 36
    },
    "pageNumbers": false,
    "paperSize": "a4"
  },
  "mobi": {
    "fontSize": 12,
    "footerTemplate": null,
    "headerTemplate": null,
    "margin": {
      "bottom": 36,
      "left": 62,
      "right": 62,
      "top": 36
    },
    "pageNumbers": false,
    "paperSize": "a4"
  },
  "plugins": [
    "disqus",
    "advanced-emoji",
    "github",
    "github-buttons",
    "emphasize",
    "splitter",
    "tbfed-pagefooter",
    "expandable-chapters-small",
    "donate",
    "anchors",
    "multipart",
    "anchor-navigation",
    "summary"
  ],
  "pluginsConfig": {
    "disqus": {
      "shortName": "morethink"
    },
    "github": {
      "url": "https://github.com/morethink"
    },
    "github-buttons": {
      "repo": "morethink/programming",
      "types": [
        "star",
        "watch",
        "fork"
      ],
      "size": "small"
    },
    "tbfed-pagefooter": {
      "copyright": "Copyright &copy 李文浩 2017",
      "modify_label": "文章最后修改时间：",
      "modify_format": "YYYY-MM-DD HH:mm:ss"
    },
    "donate": {
      "wechat": "http://images.morethink.cn//wechat-reward-image.png",
      "alipay": "http://images.morethink.cn/alipay-reward-image.jpg",
      "title": "",
      "button": "赏",
      "alipayText": "支付宝打赏",
      "wechatText": "微信打赏"
    },
    "pluginsConfig": {
      "expandable-chapters-small": {}
    }
  },
  "styles": {
    "website": "styles/website.css",
    "ebook": "styles/ebook.css",
    "pdf": "styles/pdf.css",
    "mobi": "styles/mobi.css",
    "epub": "styles/epub.css"
  },
  "variables": {}
}

```

**Comment by julianxhokaxhiu** [comment]
Well looks like to me that this plugin is doing its job fine. Although not sure what is going on in your project that it doesn't appear.

But, as your Summary looks complete to me, I can consider this issue as NOT an issue :)
