### ISSUE TITLE
输出的是平级的

### ISSUE THREAD

**Issue by anlia260** [julianxhokaxhiu/gitbook-plugin-summary#7]
输出的是平级的

**Comment by zpfang** [comment]
我采用的是作者示例中的README.md以0-开头(0-README.md), 其它文件或者文件夹依次排序的方式,
输出是期望的方式.

**Comment by zpfang** [comment]
我采用的是作者示例中的README.md以0-开头(0-README.md), 其它文件或者文件夹依次排序的方式,
输出是期望的方式.

**Comment by julianxhokaxhiu** [comment]
I am sorry but I am forced to close this issue. I do not speak Chinese.

**Comment by snow212-cn** [comment]
@julianxhokaxhiu 
He means the output summary is flattened, no subtrees. I have the same problem

**Comment by julianxhokaxhiu** [comment]
Please try again, a completely new version was released. If this happens, pleas provide some artifacts ( examples, screenshots o whatever helps ) in order to provide more help here. Thank you.
